const DAYS=['Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado','Domingo'];
const SHORT=['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'];
const meals={
'Segunda-feira':['Pão integral (1 fatia) + 3 ovos mexidos + mamão','1 maçã + castanhas (punhado) + 1 fatia de queijo branco','Arroz integral + frango grelhado (150g) + brócolis e cenoura + salada verde','Iogurte natural + whey ou 2 col. de cottage + banana','Sopa de legumes com peito de frango desfiado (porção generosa)'],
'Terça-feira':['Tapioca com queijo branco + 2 ovos + suco de laranja natural','Iogurte natural + morangos + castanhas','Batata doce + peixe assado (150g) + abobrinha refogada + salada','1 pera + amêndoas + 1 fatia de queijo branco','Salada grande + omelete de legumes (3 ovos)'],
'Quarta-feira':['Aveia com leite desnatado + banana amassada + 1 col. de whey','1 fatia de melão + 2 castanhas do Pará + iogurte','Arroz integral + lentilha + peito de frango grelhado (150g) + salada de folhas','Iogurte natural + granola sem açúcar + castanhas','Legumes grelhados + 3 ovos cozidos'],
'Quinta-feira':['Pão integral + 2 ovos + queijo branco + mamão','1 banana + pasta de amendoim natural + iogurte','Batata doce + peixe grelhado (150g) + couve refogada + salada','Vitamina de frutas com leite desnatado + whey (opcional)','Sopa de abóbora com frango desfiado (porção generosa)'],
'Sexta-feira':['Tapioca + 2 ovos + suco de melancia','Iogurte natural + uvas + castanhas','Arroz integral + frango grelhado (150g) + berinjela + salada verde','1 maçã + castanhas + queijo branco','Omelete de legumes (3 ovos) + salada'],
'Sábado':['Aveia com frutas vermelhas + leite desnatado + whey','1 fatia de abacaxi + castanhas','Batata doce + peixe assado (150g) + legumes no vapor + salada','Iogurte natural + banana + granola','Salada completa + 3 ovos cozidos'],
'Domingo':['Pão integral + 3 ovos mexidos + fruta da estação','Castanhas + 1 fruta + iogurte','Arroz integral + frango grelhado (150g) + legumes variados + salada','Vitamina de frutas + whey (opcional)','Sopa de legumes leve com frango desfiado']};
const mealNames=['Café da manhã','Lanche da manhã','Almoço','Lanche da tarde','Jantar'];
const exercises={
'Segunda-feira':['🚶','Caminhada leve','15 minutos, ritmo tranquilo','Consiga conversar sem ficar ofegante'],
'Terça-feira':['🧘','Descanso ativo / Alongamento','10 minutos','Alongue pernas, costas e ombros'],
'Quarta-feira':['🚶','Caminhada leve','15 minutos, ritmo tranquilo','Hidrate-se bem antes e depois'],
'Quinta-feira':['🧘','Descanso ativo / Alongamento','10 minutos','Respiração calma, sem pressa'],
'Sexta-feira':['🚶','Caminhada leve','15 minutos, ritmo tranquilo','Use tênis confortável'],
'Sábado':['🏊','Caminhada leve ou hidroginástica','20 minutos','Opção de baixo impacto para as articulações'],
'Domingo':['🛌','Descanso','Recuperação total','Hoje é dia de recuperar o corpo']};
const dateKey=()=>new Date().toISOString().slice(0,10);
let state=JSON.parse(localStorage.getItem('p44-state')||'null')||{water:{},meals:{},exercise:{},weights:[{date:dateKey(),value:137}]};
let selectedFood=todayName(),selectedExercise=todayName();
function todayName(){let d=new Date().getDay();return DAYS[(d+6)%7]}
function save(){localStorage.setItem('p44-state',JSON.stringify(state));renderAll()}
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.page));
document.querySelectorAll('.mission').forEach(b=>b.onclick=()=>nav({food:'alimentacao',water:'agua',exercise:'exercicios'}[b.dataset.task]));
function renderDaySelectors(){
 document.getElementById('foodDays').innerHTML=DAYS.map((d,i)=>`<button class="${d===selectedFood?'active':''}" data-day="${d}">${SHORT[i]}</button>`).join('');
 document.querySelectorAll('#foodDays button').forEach(b=>b.onclick=()=>{selectedFood=b.dataset.day;renderDaySelectors();renderMeals()});
 document.getElementById('exerciseDays').innerHTML=DAYS.map((d,i)=>`<button class="${d===selectedExercise?'active':''}" data-day="${d}">${SHORT[i]}</button>`).join('');
 document.querySelectorAll('#exerciseDays button').forEach(b=>b.onclick=()=>{selectedExercise=b.dataset.day;renderDaySelectors();renderExercise()});
}
function renderMeals(){let key=dateKey()+'|'+selectedFood;let done=state.meals[key]||[];document.getElementById('mealList').innerHTML=meals[selectedFood].map((m,i)=>`<button class="meal card ${done.includes(i)?'completed':''}" data-i="${i}"><span class="meal-check">${done.includes(i)?'✓':''}</span><div><h3>${mealNames[i]}</h3><p>${m}</p></div></button>`).join('');document.querySelectorAll('.meal').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;let arr=state.meals[key]||[];state.meals[key]=arr.includes(i)?arr.filter(x=>x!==i):[...arr,i];save()})}
function renderWater(){let n=state.water[dateKey()]||0;n=Math.max(0,Math.min(10,n));document.getElementById('waterCount').textContent=n;document.getElementById('waterHome').textContent=n;document.getElementById('waterLiters').textContent=(n*.25).toFixed(2).replace('.',',')+' L consumidos';document.getElementById('waterCups').innerHTML=Array.from({length:10},(_,i)=>`<div class="cup ${i<n?'filled':''}">💧</div>`).join('')}
document.getElementById('addWater').onclick=()=>{state.water[dateKey()]=Math.min(10,(state.water[dateKey()]||0)+1);save()};document.getElementById('removeWater').onclick=()=>{state.water[dateKey()]=Math.max(0,(state.water[dateKey()]||0)-1);save()};
function renderExercise(){let e=exercises[selectedExercise],done=!!state.exercise[dateKey()+'|'+selectedExercise];document.getElementById('exerciseCard').innerHTML=`<div class="icon">${e[0]}</div><h3>${e[1]}</h3><span class="badge">${e[2]}</span><p>${e[3]}</p>${done?'<strong style="color:#16a34a">✓ Concluído</strong>':''}`;let btn=document.getElementById('completeExercise');btn.textContent=done?'Desmarcar exercício':'Marcar exercício como concluído';document.getElementById('exerciseHome').textContent=exercises[todayName()][1]+' — '+exercises[todayName()][2]}
document.getElementById('completeExercise').onclick=()=>{let k=dateKey()+'|'+selectedExercise;state.exercise[k]=!state.exercise[k];save()};
function renderWeight(){let last=state.weights[state.weights.length-1]?.value||137;document.getElementById('currentWeight').textContent=last.toFixed(1).replace('.',',')+' kg';let lost=Math.max(0,137-last),target=7,pct=Math.min(100,Math.round(lost/target*100));document.getElementById('weightProgress').style.width=pct+'%';document.getElementById('progressPercent').textContent=pct+'%';document.getElementById('remainingText').textContent=last<=130?'Meta de 130 kg alcançada!':`Faltam ${(last-130).toFixed(1).replace('.',',')} kg`;document.getElementById('weightHistory').innerHTML=[...state.weights].reverse().map(w=>`<div class="history-item card"><div><strong>${w.value.toFixed(1).replace('.',',')} kg</strong><small>${new Date(w.date+'T12:00').toLocaleDateString('pt-BR')}</small></div><span>⚖️</span></div>`).join('');drawChart()}
document.getElementById('saveWeight').onclick=()=>{let input=document.getElementById('weightInput');let v=parseFloat(input.value.replace(',','.'));if(!v||v<30||v>300){alert('Digite um peso válido.');return}state.weights.push({date:dateKey(),value:v});input.value='';save()};
document.getElementById('clearData').onclick=()=>{if(confirm('Apagar todo o histórico e reiniciar em 137 kg?')){state.weights=[{date:dateKey(),value:137}];save()}};
function drawChart(){let c=document.getElementById('weightChart'),ctx=c.getContext('2d'),d=state.weights.slice(-12);ctx.clearRect(0,0,c.width,c.height);ctx.font='24px system-ui';ctx.fillStyle='#6b7280';if(d.length<2){ctx.fillText('Registre novos pesos para formar o gráfico.',30,180);return}let pad=48,vals=d.map(x=>x.value),min=Math.min(...vals)-1,max=Math.max(...vals)+1;ctx.strokeStyle='#e5e7eb';ctx.lineWidth=2;for(let i=0;i<4;i++){let y=pad+i*(c.height-2*pad)/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(c.width-pad,y);ctx.stroke()}ctx.strokeStyle='#f97316';ctx.lineWidth=7;ctx.lineJoin='round';ctx.beginPath();d.forEach((x,i)=>{let px=pad+i*(c.width-2*pad)/(d.length-1),py=pad+(max-x.value)/(max-min)*(c.height-2*pad);i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#f97316';d.forEach((x,i)=>{let px=pad+i*(c.width-2*pad)/(d.length-1),py=pad+(max-x.value)/(max-min)*(c.height-2*pad);ctx.beginPath();ctx.arc(px,py,8,0,Math.PI*2);ctx.fill()})}
function renderScore(){let key=dateKey()+'|'+todayName(),mealsDone=(state.meals[key]||[]).length,water=state.water[dateKey()]||0,ex=state.exercise[key]?1:0;let score=Math.round(mealsDone/5*40+water/10*30+ex*30);document.getElementById('scoreValue').textContent=score;document.getElementById('streak').textContent=score===100?'1 dia':'0 dias'}
function renderAll(){renderDaySelectors();renderMeals();renderWater();renderExercise();renderWeight();renderScore()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');renderAll();
